### ISSUE TITLE
Is this library functional yet?

### ISSUE THREAD

**Issue by nathan-chappell** [graknlabs/client-nodejs#133]
I got pointed here by the  [grakn website](https://dev.grakn.ai/docs/client-api/nodejs#installation), but when I try to `require` the library I just get `MODULE_NOT_FOUND`.  There's no `index.js` or `main` field in the `package.json`, and all the tags indicate `alpha` state...  I guess it's not ready yet?  If you guys know anyone who manages the grakn website, maybe they should update/ change their documentation?

Thanks.

**Comment by lolski** [comment]
Hi @nathan-chappell, apologies for the bad experience you're having.

Assuming you're running Grakn Core 1.8.4, please try the latest **stable** version of `grakn-client` 1.8.0: https://www.npmjs.com/package/grakn-client/v/1.8.0.

Please let me know how it goes!

**Comment by nathan-chappell** [comment]
@lolski thanks for the tip, I'll let you know!

**Comment by flyingsilverfin** [comment]
hi @nathan-chappell , is this issue still relevant to you? cheers

**Comment by haikalpribadi** [comment]
I think @lolski has addressed this issue in his response, @flyingsilverfin . I shall close this issue for now.
