### ISSUE TITLE
Typescript Definition file needed

### ISSUE THREAD

**Issue by MichaelNino** [graknlabs/client-nodejs#82]
## Problem to Solve

Need Typescript definitions

## Current Workaround

None

## Proposed Solution

Create Typescript definition file(s)

## Additional Information

See https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by MichaelNino** [comment]
Any idea if this request might be accomplished in the near future? We would like to consume Grank in upcoming project.

**Comment by flyingsilverfin** [comment]
I don't think we have the bandwitdh to implement and maintain this ourselves right now. That being said, I believe the bindings would be relatively easy to create for your use case! Perhaps we can help you collaborate and design the bindings and contribute them as an open source project?

**Comment by flyingsilverfin** [comment]
@sorsaffari  would be the one to talk to as he has the relevant experience.

**Comment by sorsaffari** [comment]
I agree @flyingsilverfin.

A PR to this repo or [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) would be much appreciated @MichaelNino.

**Comment by MichaelNino** [comment]
Okay I'll create the definition files. Thank you for technically supporting
me.

**Comment by MichaelNino** [comment]
Hi @sorsaffari 

I have begun writing the Typescript definition. Below is the definition file so I might better ask my questions.


```
// Type definitions for grakn-client 1.6.0
// Project: Grakn Client API: NodeJS
// Definitions by: Michael Niño https://www.michaelnino.com

export = GraknClient;

interface Credentials {
    username: string;
    password: string;
}

interface KeyspacesResponse {
   retrieve(): Promise<any>;
   delete(keyspace: string): Promise<any>;
}

declare class GraknClient {
    constructor(uri: string, credentials?: Credentials);

    session(keyspace: string): Session;

    /*
    this.keyspaces = () => ({
        delete: (keyspace) => keyspaceService.delete(keyspace),
        retrieve: () => keyspaceService.retrieve()
    });
    */
    keyspaces(): KeyspacesResponse[];

    close(): void;
}

/*
module.exports.dataType = {
    STRING: messages.AttributeType.DATA_TYPE.STRING,
    BOOLEAN: messages.AttributeType.DATA_TYPE.BOOLEAN,
    INTEGER: messages.AttributeType.DATA_TYPE.INTEGER,
    LONG: messages.AttributeType.DATA_TYPE.LONG,
    FLOAT: messages.AttributeType.DATA_TYPE.FLOAT,
    DOUBLE: messages.AttributeType.DATA_TYPE.DOUBLE,
    DATE: messages.AttributeType.DATA_TYPE.DATE
};
 */
declare namespace GraknClient {
    export interface dataType {
        STRING: any;
        BOOLEAN: any;
        INTEGER: any;
        LONG: any;
        FLOAT: any;
        DOUBLE: any;
        DATE: any;
    }
}
```

I have included comments from the your project's JavaScript source file for reference as well.

1. Could you elaborate on your intention to destructure object literals in the method `keyspaces`. I would like to better understand the approach so I may create necessary typing but not over-typing.
2. Could you provide me with the URL to the declaration of `messages.AttributeType.DATA` so I might create the correct types for that part of the Typescript definition? Thank you I couldn't easily locate it.

Thanks for your assistance. I think this definition file will increase overall adoption of Grakn/NodeJS.

**Comment by MichaelNino** [comment]
@sorsaffari you input would be greatly appreciated :-)

**Comment by MichaelNino** [comment]
> Perhaps we can help you collaborate and design the bindings and contribute them as an open source project?

Perhaps @flyingsilverfin. Not sure if @sorsaffari could reply. I have been waiting almost 3 yrs. to begin using Grakn. Will anyone be interested in answering a couple of questions (above).

**Comment by sorsaffari** [comment]
Hi @MichaelNino. Sorry for the late response. I'll be back at the office on the 28th and will attend to this right away.

Thank you for willing to contribute the type definitions to Client Node.js. I'm sure this will be much appreciated by the community :)

**Comment by MichaelNino** [comment]
Got it! :-) Thanks again for your guidance.

**Comment by sorsaffari** [comment]
> Could you elaborate on your intention to destructure object literals in the method keyspaces.

There isn't a specific reason for it. It's been the design the decision made initially for [Client Java](https://github.com/graknlabs/client-java/blob/master/GraknClient.java#L133) which then has been replicated in the other clients.

> Could you provide me with the URL to the declaration of messages.AttributeType.DATA

Here is the [`enum Datatype` within `Concept.proto`](https://github.com/graknlabs/protocol/blob/master/session/Concept.proto#L507-L515) of [`graknlabs/protocol`](https://github.com/graknlabs/protocol).

> The method "keyspaces" is plural. Are we intending to destructure to an array of object literals?
Despite its plurality, [`keyspaces()`](https://github.com/graknlabs/client-nodejs/blob/master/src/GraknClient.js#L50-L53) returns a single object. It's a bit confusing, I know, but I kind of see why it's been made plural considering the methods that can be called on the object it returns (i.e. `delete` and `retrieve`)

Once again, thanks for the effort @MichaelNino and do let me know if any of these answers are unclear or if you have any more questions :)

**Comment by MichaelNino** [comment]
Awesome! I was counting the days ;-) until your response! 

Thank you for the clarification. I am very happy to contribute.

**Comment by tchupp** [comment]
Hi! I'm very interested in using Grakn with a NodeJS project I'm working on, written in TypeScript.
Is there anything I could do to help make this Type Def file happen?

**Comment by alexjpwalker** [comment]
The NodeJS client for Grakn 2.0 is a TypeScript project, and the `npm` package `grakn-client` contains both `.js` and `.d.ts` files as of 2.0.
